### PR TITLE
Don't add .gitignore

### LINKED ISSUE #1: autoignore adds .gitignore to .gitignore if it hasn't been added yet

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #1

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Still needs a test

**Review by adamhutchings — APPROVED** [review]
LGTM!

**Comment by JakeRoggenbuck** [comment]
Merge?

**Comment by JakeRoggenbuck** [comment]
Poke

**Pull request merged**
